import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import NavbarComponent from "@/components/NavbarComponent/NavbarComponent";
import FooterComponent from "@/components/FooterComponet/FooterComponent";
import StoreProvider from "../StoreProvider";
import SessionWrapper from "../SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className={inter.className}>
          <StoreProvider>
            <NavbarComponent />
            {children}
            <FooterComponent />
          </StoreProvider>
        </body>
      </SessionWrapper>
    </html>
  );
}
